<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Area Code' => '地区代码',
    'ID' => '',
    'ISO 639 1' => '',
    'ISO 639 2' => '',
    'ISO 639 3' => '',
    'Post Code' => '邮编',
    'Active' => '可用',
    'Add SubCategory' => '添加子栏目',
    'Add subArea' => '添加子地区',
    'Allow Publish' => '允许发布',
    'Area "{value}" not found.' => '地区 "{value}" 不存在。',
    'Area ID' => '地区ID',
    'Area Name' => '地区名称',
    'Area Sort' => '地区排序',
    'Category Description' => '描述',
    'Category Keywords' => '关键词',
    'Category Name' => '名称',
    'Category Slug' => '标识',
    'Content' => '内容',
    'Create' => '创建',
    'Create Area' => '创建地区',
    'Create Category' => '创建栏目',
    'Create Language' => '创建语言',
    'Create Page' => '创建页面',
    'Create Url Rule' => '创建Url规则',
    'Created At' => '创建时间',
    'Delete Area' => '删除地区',
    'Delete Category' => '删除栏目',
    'Delete Language' => '删除语言',
    'Delete Page' => '删除页面',
    'Delete Url Rule' => '删除Url规则',
    'Description' => '描述',
    'Disable' => '禁用',
    'Frequency' => '热度',
    'Keywords' => '关键词',
    'Language Name' => '语言名称',
    'Letter' => '首字母',
    'Loop detected.' => '死循环了。',
    'Manage Area' => '地区管理',
    'Manage Category' => '栏目管理',
    'Manage Language' => '语言管理',
    'Manage Page' => '页面管理',
    'Manage Url Rule' => 'Url规则管理',
    'Module' => '模块',
    'Params' => '参数',
    'Parent Area' => '父地区',
    'Parent Area Name' => '父地区',
    'Parent Category' => '父栏目',
    'Parent Type' => '父类别',
    'Pinyin' => '拼音',
    'Published in' => '发布于',
    'Redirect' => '转向',
    'Redirect Code' => '转向代码',
    'Route' => '路由',
    'Slug' => 'Path',
    'Sort' => '排序',
    'Status' => '状态',
    'This iso_639_1 has already been taken' => '该 ISO 639 1 已被使用。',
    'This iso_639_2 has already been taken' => '该 ISO 639 2 已被使用。',
    'This iso_639_3 has already been taken' => '该 ISO 639 3 已被使用。',
    'This name has already been taken' => '该名称已被使用。',
    'Title' => '标题',
    'Type Name' => '类别名称',
    'Update' => '更新',
    'Update Area' => '更新地区',
    'Update Category' => '更新栏目',
    'Update Language' => '更新语言',
    'Update Page' => '更新页面',
    'Update Url Rule' => '更新Url规则',
    'Updated At' => '更新时间',
    'User Id' => '用户ID',
    'View' => '视图',
    'Views' => '查看次数',
    '{attribute} Do not meet the rules.' => '{attribute} 不符合规则。',
];
