<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Published in' => '发布于',
    'Active' => '可用',
    'Content' => '内容',
    'Create Page' => '创建页面',
    'Create Url Rule' => '创建Url规则',
    'Created At' => '创建时间',
    'Delete Page' => '删除页面',
    'Delete Url Rule' => '删除Url规则',
    'Description' => '描述',
    'Disable' => '禁用',
    'ID' => '',
    'Keywords' => '关键词',
    'Manage Page' => '页面管理',
    'Manage Url Rule' => 'Url规则管理',
    'Params' => '参数',
    'Redirect' => '转向',
    'Redirect Code' => '转向代码',
    'Route' => '路由',
    'Slug' => 'Path',
    'Status' => '状态',
    'Title' => '标题',
    'Update Page' => '更新页面',
    'Update Url Rule' => '更新Url规则',
    'Updated At' => '更新时间',
    'User Id' => '用户ID',
    'View' => '视图',
    'Views' => '查看次数',
];
