<?php

namespace yuncms\migrations;

use yii\db\Migration;

class M161221092135Create_currencies_table extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }
        //https://www.iso.org/obp/ui/#search
        $this->createTable('{{%currencies}}', [
            'id' => $this->primaryKey(11),
            //English short name
            'name' => $this->string()->notNull()->unique(),
            'code' => $this->string(10)->notNull()->unique(),
            'numeric' => $this->integer(3)->notNull()->unique(),
            'decimals' => $this->string(10),
        ], $tableOptions);

        $this->batchInsert('{{%currencies}}', ['name', 'code', 'numeric', 'decimals'], [
            ['United Arab Emirates dirham', 'AED', '784', '2'],
            ['Afghan afghani', 'AFN', '971', '2'],
            ['Albanian lek', 'ALL', '8', '2'],
            ['Armenian dram', 'AMD', '51', '2'],
            ['Netherlands Antillean guilder', 'ANG', '532', '2'],
            ['Angolan kwanza', 'AOA', '973', '2'],
            ['Argentine peso', 'ARS', '32', '2'],
            ['Australian dollar', 'AUD', '36', '2'],
            ['Aruban florin', 'AWG', '533', '2'],
            ['Azerbaijani manat', 'AZN', '944', '2'],
            ['Bosnia and Herzegovina convertible mark', 'BAM', '977', '2'],
            ['Barbados dollar', 'BBD', '52', '2'],
            ['Bangladeshi taka', 'BDT', '50', '2'],
            ['Bulgarian lev', 'BGN', '975', '2'],
            ['Bahraini dinar', 'BHD', '48', '3'],
            ['Burundian franc', 'BIF', '108', '0'],
            ['Bermudian dollar', 'BMD', '60', '2'],
            ['Brunei dollar', 'BND', '96', '2'],
            ['Boliviano', 'BOB', '68', '2'],
            ['Bolivian Mvdol (funds code)', 'BOV', '984', '2'],
            ['Brazilian real', 'BRL', '986', '2'],
            ['Bahamian dollar', 'BSD', '44', '2'],
            ['Bhutanese ngultrum', 'BTN', '64', '2'],
            ['Botswana pula', 'BWP', '72', '2'],
            ['New Belarusian ruble', 'BYN', '933', '2'],
            ['Belarusian ruble', 'BYR', '974', '0'],
            ['Belize dollar', 'BZD', '84', '2'],
            ['Canadian dollar', 'CAD', '124', '2'],
            ['Congolese franc', 'CDF', '976', '2'],
            ['WIR Euro (complementary currency)', 'CHE', '947', '2'],
            ['Swiss franc', 'CHF', '756', '2'],
            ['WIR Franc (complementary currency)', 'CHW', '948', '2'],
            ['Unidad de Fomento (funds code)', 'CLF', '990', '4'],
            ['Chilean peso', 'CLP', '152', '0'],
            ['Chinese yuan', 'CNY', '156', '2'],
            ['Colombian peso', 'COP', '170', '2'],
            ['Unidad de Valor Real (UVR) (funds code)[7]', 'COU', '970', '2[7]'],
            ['Costa Rican colon', 'CRC', '188', '2'],
            ['Cuban convertible peso', 'CUC', '931', '2'],
            ['Cuban peso', 'CUP', '192', '2'],
            ['Cape Verde escudo', 'CVE', '132', '0'],
            ['Czech koruna', 'CZK', '203', '2'],
            ['Djiboutian franc', 'DJF', '262', '0'],
            ['Danish krone', 'DKK', '208', '2'],
            ['Dominican peso', 'DOP', '214', '2'],
            ['Algerian dinar', 'DZD', '12', '2'],
            ['Egyptian pound', 'EGP', '818', '2'],
            ['Eritrean nakfa', 'ERN', '232', '2'],
            ['Ethiopian birr', 'ETB', '230', '2'],
            ['Euro', 'EUR', '978', '2'],
            ['Fiji dollar', 'FJD', '242', '2'],
            ['Falkland Islands pound', 'FKP', '238', '2'],
            ['Pound sterling', 'GBP', '826', '2'],
            ['Georgian lari', 'GEL', '981', '2'],
            ['Ghanaian cedi', 'GHS', '936', '2'],
            ['Gibraltar pound', 'GIP', '292', '2'],
            ['Gambian dalasi', 'GMD', '270', '2'],
            ['Guinean franc', 'GNF', '324', '0'],
            ['Guatemalan quetzal', 'GTQ', '320', '2'],
            ['Guyanese dollar', 'GYD', '328', '2'],
            ['Hong Kong dollar', 'HKD', '344', '2'],
            ['Honduran lempira', 'HNL', '340', '2'],
            ['Croatian kuna', 'HRK', '191', '2'],
            ['Haitian gourde', 'HTG', '332', '2'],
            ['Hungarian forint', 'HUF', '348', '2'],
            ['Indonesian rupiah', 'IDR', '360', '2'],
            ['Israeli new shekel', 'ILS', '376', '2'],
            ['Indian rupee', 'INR', '356', '2'],
            ['Iraqi dinar', 'IQD', '368', '3'],
            ['Iranian rial', 'IRR', '364', '2'],
            ['Icelandic króna', 'ISK', '352', '0'],
            ['Jamaican dollar', 'JMD', '388', '2'],
            ['Jordanian dinar', 'JOD', '400', '3'],
            ['Japanese yen', 'JPY', '392', '0'],
            ['Kenyan shilling', 'KES', '404', '2'],
            ['Kyrgyzstani som', 'KGS', '417', '2'],
            ['Cambodian riel', 'KHR', '116', '2'],
            ['Comoro franc', 'KMF', '174', '0'],
            ['North Korean won', 'KPW', '408', '2'],
            ['South Korean won', 'KRW', '410', '0'],
            ['Kuwaiti dinar', 'KWD', '414', '3'],
            ['Cayman Islands dollar', 'KYD', '136', '2'],
            ['Kazakhstani tenge', 'KZT', '398', '2'],
            ['Lao kip', 'LAK', '418', '2'],
            ['Lebanese pound', 'LBP', '422', '2'],
            ['Sri Lankan rupee', 'LKR', '144', '2'],
            ['Liberian dollar', 'LRD', '430', '2'],
            ['Lesotho loti', 'LSL', '426', '2'],
            ['Libyan dinar', 'LYD', '434', '3'],
            ['Moroccan dirham', 'MAD', '504', '2'],
            ['Moldovan leu', 'MDL', '498', '2'],
            ['Malagasy ariary', 'MGA', '969', '1*[9]'],
            ['Macedonian denar', 'MKD', '807', '2'],
            ['Myanmar kyat', 'MMK', '104', '2'],
            ['Mongolian tögrög', 'MNT', '496', '2'],
            ['Macanese pataca', 'MOP', '446', '2'],
            ['Mauritanian ouguiya', 'MRO', '478', '1*[9]'],
            ['Mauritian rupee', 'MUR', '480', '2'],
            ['Maldivian rufiyaa', 'MVR', '462', '2'],
            ['Malawian kwacha', 'MWK', '454', '2'],
            ['Mexican peso', 'MXN', '484', '2'],
            ['Mexican Unidad de Inversion (UDI) (funds code)', 'MXV', '979', '2'],
            ['Malaysian ringgit', 'MYR', '458', '2'],
            ['Mozambican metical', 'MZN', '943', '2'],
            ['Namibian dollar', 'NAD', '516', '2'],
            ['Nigerian naira', 'NGN', '566', '2'],
            ['Nicaraguan córdoba', 'NIO', '558', '2'],
            ['Norwegian krone', 'NOK', '578', '2'],
            ['Nepalese rupee', 'NPR', '524', '2'],
            ['New Zealand dollar', 'NZD', '554', '2'],
            ['Omani rial', 'OMR', '512', '3'],
            ['Panamanian balboa', 'PAB', '590', '2'],
            ['Peruvian Sol', 'PEN', '604', '2'],
            ['Papua New Guinean kina', 'PGK', '598', '2'],
            ['Philippine peso', 'PHP', '608', '2'],
            ['Pakistani rupee', 'PKR', '586', '2'],
            ['Polish złoty', 'PLN', '985', '2'],
            ['Paraguayan guaraní', 'PYG', '600', '0'],
            ['Qatari riyal', 'QAR', '634', '2'],
            ['Romanian leu', 'RON', '946', '2'],
            ['Serbian dinar', 'RSD', '941', '2'],
            ['Russian ruble', 'RUB', '643', '2'],
            ['Rwandan franc', 'RWF', '646', '0'],
            ['Saudi riyal', 'SAR', '682', '2'],
            ['Solomon Islands dollar', 'SBD', '90', '2'],
            ['Seychelles rupee', 'SCR', '690', '2'],
            ['Sudanese pound', 'SDG', '938', '2'],
            ['Swedish krona/kronor', 'SEK', '752', '2'],
            ['Singapore dollar', 'SGD', '702', '2'],
            ['Saint Helena pound', 'SHP', '654', '2'],
            ['Sierra Leonean leone', 'SLL', '694', '2'],
            ['Somali shilling', 'SOS', '706', '2'],
            ['Surinamese dollar', 'SRD', '968', '2'],
            ['South Sudanese pound', 'SSP', '728', '2'],
            ['São Tomé and Príncipe dobra', 'STD', '678', '2'],
            ['Salvadoran colón', 'SVC', '222', '2'],
            ['Syrian pound', 'SYP', '760', '2'],
            ['Swazi lilangeni', 'SZL', '748', '2'],
            ['Thai baht', 'THB', '764', '2'],
            ['Tajikistani somoni', 'TJS', '972', '2'],
            ['Turkmenistani manat', 'TMT', '934', '2'],
            ['Tunisian dinar', 'TND', '788', '3'],
            ['Tongan paʻanga', 'TOP', '776', '2'],
            ['Turkish lira', 'TRY', '949', '2'],
            ['Trinidad and Tobago dollar', 'TTD', '780', '2'],
            ['New Taiwan dollar', 'TWD', '901', '2'],
            ['Tanzanian shilling', 'TZS', '834', '2'],
            ['Ukrainian hryvnia', 'UAH', '980', '2'],
            ['Ugandan shilling', 'UGX', '800', '0'],
            ['United States dollar', 'USD', '840', '2'],
            ['United States dollar (next day) (funds code)', 'USN', '997', '2'],
            ['Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)', 'UYI', '940', '0'],
            ['Uruguayan peso', 'UYU', '858', '2'],
            ['Uzbekistan som', 'UZS', '860', '2'],
            ['Venezuelan bolívar', 'VEF', '937', '2'],
            ['Vietnamese dong', 'VND', '704', '0'],
            ['Vanuatu vatu', 'VUV', '548', '0'],
            ['Samoan tala', 'WST', '882', '2'],
            ['CFA franc BEAC', 'XAF', '950', '0'],
            ['Silver (one troy ounce)', 'XAG', '961', '0'],
            ['Gold (one troy ounce)', 'XAU', '959', '0'],
            ['European Composite Unit (EURCO) (bond market unit)', 'XBA', '955', '0'],
            ['European Monetary Unit (E.M.U.-6) (bond market unit)', 'XBB', '956', '0'],
            ['European Unit of Account 9 (E.U.A.-9) (bond market unit)', 'XBC', '957', '0'],
            ['European Unit of Account 17 (E.U.A.-17) (bond market unit)', 'XBD', '958', '0'],
            ['East Caribbean dollar', 'XCD', '951', '2'],
            ['Special drawing rights', 'XDR', '960', '0'],
            ['CFA franc BCEAO', 'XOF', '952', '0'],
            ['Palladium (one troy ounce)', 'XPD', '964', '0'],
            ['CFP franc (franc Pacifique)', 'XPF', '953', '0'],
            ['Platinum (one troy ounce)', 'XPT', '962', '0'],
            ['SUCRE', 'XSU', '994', '0'],
            ['Code reserved for testing purposes', 'XTS', '963', '0'],
            ['ADB Unit of Account', 'XUA', '965', '0'],
            ['No currency', 'XXX', '999', '0'],
            ['Yemeni rial', 'YER', '886', '2'],
            ['South African rand', 'ZAR', '710', '2'],
            ['Zambian kwacha', 'ZMW', '967', '2'],
            ['Zimbabwean dollar A/10', 'ZWL', '932', '2'],
            ['Internet', 'BTC', 'null', '8'],
        ]);
    }

    public function down()
    {
        $this->dropTable('{{%currencies}}');
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
