<?php

namespace yuncms\system\migrations;

use yii\db\Migration;

class M161221090448Create_languages_table extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%languages}}', [
            'id' => $this->primaryKey(11),
            'name' => $this->string()->notNull()->unique(),
            'iso_639_1' => $this->string(2)->notNull()->unique(),
            'iso_639_2' => $this->string(10)->notNull()->unique(),
            'iso_639_3' => $this->string(10)->notNull()->unique(),
        ], $tableOptions);

        $this->batchInsert('{{%languages}}', ['name', 'iso_639_1', 'iso_639_2', 'iso_639_3'], [
            ['Afar', 'aa', 'aar', 'aar'],
            ['Abkhazian', 'ab', 'abk', 'abk'],
            ['Avestan', 'ae', 'ave', 'ave'],
            ['Afrikaans', 'af', 'afr', 'afr'],
            ['Akan', 'ak', 'aka', 'aka'],
            ['Amharic', 'am', 'amh', 'amh'],
            ['Aragonese', 'an', 'arg', 'arg'],
            ['Arabic', 'ar', 'ara', 'ara'],
            ['Assamese', 'as', 'asm', 'asm'],
            ['Avaric', 'av', 'ava', 'ava'],
            ['Aymara', 'ay', 'aym', 'aym'],
            ['Azerbaijani', 'az', 'aze', 'aze'],
            ['Bashkir', 'ba', 'bak', 'bak'],
            ['Belarusian', 'be', 'bel', 'bel'],
            ['Bulgarian', 'bg', 'bul', 'bul'],
            ['Bihari', 'bh', 'bih', '无'],
            ['Bislama', 'bi', 'bis', 'bis'],
            ['Bambara', 'bm', 'bam', 'bam'],
            ['Bengali', 'bn', 'ben', 'ben'],
            ['Tibetan', 'bo', 'tib/bod', 'bod'],
            ['Breton', 'br', 'bre', 'bre'],
            ['Bosnian', 'bs', 'bos', 'bos'],
            ['Catalan', 'ca', 'cat', 'cat'],
            ['Chechen', 'ce', 'che', 'che'],
            ['Chamorro', 'ch', 'cha', 'cha'],
            ['Corsican', 'co', 'cos', 'cos'],
            ['Cree', 'cr', 'cre', 'cre'],
            ['Czech', 'cs', 'cze/ces', 'ces'],
            ['Church Slavic', 'cu', 'chu', 'chu'],
            ['Chuvash', 'cv', 'chv', 'chv'],
            ['Welsh', 'cy', 'wel/cym', 'cym'],
            ['Danish', 'da', 'dan', 'dan'],
            ['German', 'de', 'ger/deu', 'deu'],
            ['Divehi', 'dv', 'div', 'div'],
            ['Dzongkha', 'dz', 'dzo', 'dzo'],
            ['Ewe', 'ee', 'ewe', 'ewe'],
            ['Greek', 'el', 'gre/ell', 'ell'],
            ['English', 'en', 'eng', 'eng'],
            ['Esperanto', 'eo', 'epo', 'epo'],
            ['Spanish; Castilian', 'es', 'spa', 'spa'],
            ['Estonian', 'et', 'est', 'est'],
            ['Basque', 'eu', 'baq/eus', 'eus'],
            ['Persian', 'fa', 'per/fas', 'fas'],
            ['Fulah', 'ff', 'ful', 'ful'],
            ['Finnish', 'fi', 'fin', 'fin'],
            ['Fijian', 'fj', 'fij', 'fij'],
            ['Faroese', 'fo', 'fao', 'fao'],
            ['French', 'fr', 'fre/fra', 'fra'],
            ['Western Frisian', 'fy', 'fry', 'fry'],
            ['Irish', 'ga', 'gle', 'gle'],
            ['Scottish Gaelic', 'gd', 'gla', 'gla'],
            ['Galician', 'gl', 'glg', 'glg'],
            ['Guaraní', 'gn', 'grn', 'grn'],
            ['Gujarati', 'gu', 'guj', 'guj'],
            ['Manx', 'gv', 'glv', 'glv'],
            ['Hausa', 'ha', 'hau', 'hau'],
            ['Hebrew', 'he', 'heb', 'heb'],
            ['Hindi', 'hi', 'hin', 'hin'],
            ['Hiri Motu', 'ho', 'hmo', 'hmo'],
            ['Croatian', 'hr', 'scr/hrv', 'hrv'],
            ['Haitian Creole', 'ht', 'hat', 'hat'],
            ['Hungarian', 'hu', 'hun', 'hun'],
            ['Armenian', 'hy', 'arm/hye', 'hye'],
            ['Herero', 'hz', 'her', 'her'],
            ['Interlingua', 'ia', 'ina', 'ina'],
            ['Indonesian', 'id', 'ind', 'ind'],
            ['Interlingue', 'ie', 'ile', 'ile'],
            ['Igbo', 'ig', 'ibo', 'ibo'],
            ['Sichuan Yi', 'ii', 'iii', 'iii'],
            ['Inupiaq', 'ik', 'ipk', 'ipk'],
            ['Ido', 'io', 'ido', 'ido'],
            ['Icelandic', 'is', 'ice/isl', 'isl'],
            ['Italian', 'it', 'ita', 'ita'],
            ['Inuktitut', 'iu', 'iku', 'iku'],
            ['Japanese', 'ja', 'jpn', 'jpn'],
            ['Javanese', 'jv', 'jav', 'jav'],
            ['Georgian', 'ka', 'geo/kat', 'kat'],
            ['Kongo', 'kg', 'kon', 'kon'],
            ['Kikuyu', 'ki', 'kik', 'kik'],
            ['Kwanyama', 'kj', 'kua', 'kua'],
            ['Kazakh', 'kk', 'kaz', 'kaz'],
            ['Kalaallisut', 'kl', 'kal', 'kal'],
            ['Khmer', 'km', 'khm', 'khm'],
            ['Kannada', 'kn', 'kan', 'kan'],
            ['Korean', 'ko', 'kor', 'kor'],
            ['Kanuri', 'kr', 'kau', 'kau'],
            ['Kashmiri', 'ks', 'kas', 'kas'],
            ['Kurdish', 'ku', 'kur', 'kur'],
            ['Komi', 'kv', 'kom', 'kom'],
            ['Cornish', 'kw', 'cor', 'cor'],
            ['Kirghiz', 'ky', 'kir', 'kir'],
            ['Latin', 'la', 'lat', 'lat'],
            ['Luxembourgish', 'lb', 'ltz', 'ltz'],
            ['Ganda', 'lg', 'lug', 'lug'],
            ['Limburgish', 'li', 'lim', 'lim'],
            ['Lingala', 'ln', 'lin', 'lin'],
            ['Lao', 'lo', 'lao', 'lao'],
            ['Lithuanian', 'lt', 'lit', 'lit'],
            ['Luba-Katanga', 'lu', 'lub', 'lub'],
            ['Latvian', 'lv', 'lav', 'lav'],
            ['Malagasy', 'mg', 'mlg', 'mlg'],
            ['Marshallese', 'mh', 'mah', 'mah'],
            ['Māori', 'mi', 'mao/mri', 'mri'],
            ['Macedonian', 'mk', 'mac/mkd', 'mkd'],
            ['Malayalam', 'ml', 'mal', 'mal'],
            ['Mongolian', 'mn', 'mon', 'mon'],
            ['Moldavian', 'mo', 'mol', 'mol'],
            ['Marathi', 'mr', 'mar', 'mar'],
            ['Malay', 'ms', 'may/msa', 'msa'],
            ['Maltese', 'mt', 'mlt', 'mlt'],
            ['Burmese', 'my', 'bur/mya', 'mya'],
            ['Nauru', 'na', 'nau', 'nau'],
            ['Norwegian Bokm?l', 'nb', 'nob', 'nob'],
            ['North Ndebele', 'nd', 'nde', 'nde'],
            ['Nepali', 'ne', 'nep', 'nep'],
            ['Ndonga', 'ng', 'ndo', 'ndo'],
            ['Dutch', 'nl', 'dut/nld', 'nld'],
            ['Norwegian Nynorsk', 'nn', 'nno', 'nno'],
            ['Norwegian', 'no', 'nor', 'nor'],
            ['South Ndebele', 'nr', 'nbl', 'nbl'],
            ['Navajo', 'nv', 'nav', 'nav'],
            ['Chichewa', 'ny', 'nya', 'nya'],
            ['Occitan', 'oc', 'oci', 'oci'],
            ['Ojibwa', 'oj', 'oji', 'oji'],
            ['Oromo', 'om', 'orm', 'orm'],
            ['Oriya', 'or', 'ori', 'ori'],
            ['Ossetian', 'os', 'oss', 'oss'],
            ['Panjabi', 'pa', 'pan', 'pan'],
            ['Pāli', 'pi', 'pli', 'pli'],
            ['Polish', 'pl', 'pol', 'pol'],
            ['Pashto', 'ps', 'pus', 'pus'],
            ['Portuguese', 'pt', 'por', 'por'],
            ['Quechua', 'qu', 'que', 'que'],
            ['Raeto-Romance', 'rm', 'roh', 'roh'],
            ['Kirundi', 'rn', 'run', 'run'],
            ['Romanian', 'ro', 'rum/ron', 'ron'],
            ['Russian', 'ru', 'rus', 'rus'],
            ['Kinyarwanda', 'rw', 'kin', 'kin'],
            ['Sanskrit', 'sa', 'san', 'san'],
            ['Sardinian', 'sc', 'srd', 'srd'],
            ['Sindhi', 'sd', 'snd', 'snd'],
            ['Northern Sami', 'se', 'sme', 'sme'],
            ['Sango', 'sg', 'sag', 'sag'],
            ['Serbo-Croatian', 'sh', '无', 'hbs'],
            ['Sinhalese', 'si', 'sin', 'sin'],
            ['Slovak', 'sk', 'slo/slk', 'slk'],
            ['Slovenian', 'sl', 'slv', 'slv'],
            ['Samoan', 'sm', 'smo', 'smo'],
            ['Shona', 'sn', 'sna', 'sna'],
            ['Somali', 'so', 'som', 'som'],
            ['Albanian', 'sq', 'alb/sqi', 'sqi'],
            ['Serbian', 'sr', 'scc/srp', 'srp'],
            ['Swati', 'ss', 'ssw', 'ssw'],
            ['Sotho', 'st', 'sot', 'sot'],
            ['Sundanese', 'su', 'sun', 'sun'],
            ['Swedish', 'sv', 'swe', 'swe'],
            ['Swahili', 'sw', 'swa', 'swa'],
            ['Tamil', 'ta', 'tam', 'tam'],
            ['Telugu', 'te', 'tel', 'tel'],
            ['Tajik', 'tg', 'tgk', 'tgk'],
            ['Thai', 'th', 'tha', 'tha'],
            ['Tigrinya', 'ti', 'tir', 'tir'],
            ['Turkmen', 'tk', 'tuk', 'tuk'],
            ['Tagalog', 'tl', 'tgl', 'tgl'],
            ['Tswana', 'tn', 'tsn', 'tsn'],
            ['Tonga', 'to', 'ton', 'ton'],
            ['Turkish', 'tr', 'tur', 'tur'],
            ['Tsonga', 'ts', 'tso', 'tso'],
            ['Tatar', 'tt', 'tat', 'tat'],
            ['Twi', 'tw', 'twi', 'twi'],
            ['Tahitian', 'ty', 'tah', 'tah'],
            ['Uyghur', 'ug', 'uig', 'uig'],
            ['Ukrainian', 'uk', 'ukr', 'ukr'],
            ['Urdu', 'ur', 'urd', 'urd'],
            ['Uzbek', 'uz', 'uzb', 'uzb'],
            ['Venda', 've', 'ven', 'ven'],
            ['Vietnamese', 'vi', 'vie', 'vie'],
            ['Volapük', 'vo', 'vol', 'vol'],
            ['Walloon', 'wa', 'wln', 'wln'],
            ['Wolof', 'wo', 'wol', 'wol'],
            ['Xhosa', 'xh', 'xho', 'xho'],
            ['Yiddish', 'yi', 'yid', 'yid'],
            ['Yoruba', 'yo', 'yor', 'yor'],
            ['Zhuang', 'za', 'zha', 'zha'],
            ['Chinese', 'zh', 'chi/zho', 'zho'],
            ['Zulu', 'zu', 'zul', 'zul'],
        ]);
    }

    public function down()
    {
        $this->dropTable('{{%languages}}');
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
